### ISSUE TITLE
Low performance on tcp rr tests

### ISSUE THREAD

**Issue by tomerr-lb** [amzn/amzn-drivers#70] opened 2018-05-07 12:17 UTC
We are trying to run our infra on AWS and we have problems optimizing the network performance.
we measured network performance using netperf (scripts repo attached) , stream and maerts tests throughput results fall very close to 25Gbits/s.
The rr test which best represent the workloads we use gives us the following results:
tx_pkt_size = 60, rx_pkt_size = 1024 , throughput := 3022Mb/s, transactions rate := 348414 transactions per second
tx_pkt_size = 60, rx_pkt_size = 4096 , throughput := 8786Mb/s, transactions rate := 264171 transactions per second
it seems like we are blocked on 348414 transactions per second.

those tests were preformed on both m4.16xlarge and i3.16xlarge instances running amazon_linux , ubuntu and our own custom images all of them shows the same results.

the interfaces in AWS are configured to jambo packets by default so I've configured the mtu to 1500 manually (ifconfig <iface name> mtu 1500).
also we noticed that while running network loads core 0 was saturated with handling network interrupts , 
after looking at this post : https://forums.aws.amazon.com/message.jspa?messageID=690448 
we changed the core affinity of the data interface to be spread across cores 0-8 (script in git).

as we are planning to handle the network in userland we tried testing with dpdk pktgen but we could only achieve 10 Gb/s throughput.

scripts can be accessed from here : https://github.com/LightBitsLabs/netperf_scripts
any help will be appreciated :)

**Comment by yastreb78** [comment] 2018-05-07 16:35
Dear @tomerr-lb,

Thanks for your inquiry. We will analyze the behavior or RR (request respond) test in netperf, and check if there is a way to improve the results. However, it's also possible that it's caused by inefficiency of the RR test itself - it handles single packet in a time. I assume that in order to reach the above transaction rate you had to run few tests in parallel. How many did you use?

Few general suggestions:
RR tests depend on latency - you can reduce latency by placing instances in the same placement group. In addition, you might consider using c5.* instances that have some reduction in latency as well.
I don't see why reducing MTU to 1500 would give any benefit

With regards to pktgen in DPDK, we identified few issues with the tests itself. In these days, we prepare DPDK based test environment which allows to demonstrate max performance from BW, PPS and latency point of view. We plan to upload this environment in this GitHub in near future.

For further communication, please provide your contact details to akiyano@amazon.com

**Comment by tomerr-lb** [comment] 2018-05-07 18:28
Hi yastreb78 ,
thanks for the quick response, I've added more information to the email.

**Comment by AWSNB** [comment] 2018-05-07 18:34
Tomer,

in addition to the previous suggestions, tcp_rr is sensitive to latency, and there are couple of instance/AMI settings that usually improve latency, especially on XEN based instances like i3.16xl and m4.16xl

1) Disabling deep power states for Intel processors helps provide lower and consistent latency, and as result throughput,  by setting intel_idle.max_cstate=1  in grub (or grub equivalent for your AMI) file.     this is covered in : https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/processor_state_control.html

2) in same grub or grub equivalent config,  use xen_nopvspin=1, which would provide additional latency saving.  unfortunately, most out-of-box OS distribution don't have this setting

good luck
NB

**Comment by tomerr-lb** [comment] 2018-05-08 06:25
Thanks I'll try it, also regarding dpdk results :
When running RX and TX flows concurrently we can only get 4Gb/s each

**Comment by AWSNB** [comment] 2018-05-08 06:28
Tomer, a single flow would typically be limited to 5Gbps or 10Gbps depending on placement group.  to achieve higher bandwidth, one would need to run multiple concurrent flows

**Comment by tomerr-lb** [comment] 2018-05-08 12:37
I've tried running with xen_novspin=1 but I cant see any improvement (max_cstate was already set to 1)
all of the instances are dedicated instances and on the same placement group.
we also tried canceling tcp_corking and Nagle .

**Comment by zorikm** [comment] 2020-08-25 17:09
@tomerr-lb 
This issue seems to be outdated. I'm closing it. Please feel free to re-open if relevant.
Thanks!

**Closed by zorikm** 2020-08-25 17:09 UTC
