### ISSUE TITLE
@adjfreq method / Adjusts the frequency of the hardware clock has removed since kernel 6.2

### ISSUE THREAD

**Issue by mehrdadrad** [amzn/amzn-drivers#269] opened 2023-05-17 17:01 UTC
### Preliminary Actions

- [X] I have searched the existing [issues](https://github.com/amzn/amzn-drivers/issues) and didn't find a duplicate.
- [X] I have followed the [AWS official troubleshoot documentation](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/troubleshooting-ena.html).
- [X] I have followed the driver [readme](https://github.com/amzn/amzn-drivers) and [best practices](https://github.com/amzn/amzn-drivers/blob/master/kernel/linux/ena/ENA_Linux_Best_Practices.rst).

### Driver Type

Linux kernel driver for Elastic Network Adapter (ENA)

### Driver Tag/Commit

ena_linux_2.8.3

### Custom Code

No

### OS Platform and Distribution

Linux 6.2.15-100.fc36.x86_64

### Bug description

[The @adjfreq / adjusts the frequency of the hardware clock](https://elixir.bootlin.com/linux/v6.1.28/source/include/linux/ptp_clock_kernel.h#L78) method has deprecated and removed since [kernel 6.2](https://elixir.bootlin.com/linux/v6.2/source/include/linux/ptp_clock_kernel.h#L57) but ena driver still has  this method [here](https://github.com/amzn/amzn-drivers/blob/master/kernel/linux/ena/ena_phc.c#L112). per kernel comment `New drivers should implement the @adjfine method instead.`

### Reproduction steps

```bash
Run the below script with kernel version 6.2:

TEMP_TOOLS="dkms git"
ENA_VER="2.8.3"
sudo dnf install -y $TEMP_TOOLS
sudo git clone -b ena_linux_$ENA_VER --depth 1 https://github.com/amzn/amzn-drivers.git /usr/src/amzn-drivers-$ENA_VER
cat << EOF | sudo tee /usr/src/amzn-drivers-$ENA_VER/dkms.conf
PACKAGE_NAME="ena"
PACKAGE_VERSION="1.0.0"
CLEAN="make -C kernel/linux/ena clean"
MAKE="ENA_PHC_INCLUDE=1 make -C kernel/linux/ena/ BUILD_KERNEL=$(uname -r)"
BUILT_MODULE_NAME[0]="ena"
BUILT_MODULE_LOCATION="kernel/linux/ena"
DEST_MODULE_LOCATION[0]="/updates"
DEST_MODULE_NAME[0]="ena"
AUTOINSTALL="yes"
EOF
sudo dkms add -m amzn-drivers -v $ENA_VER
sudo dkms build -m amzn-drivers -v $ENA_VER
sudo dkms install -m amzn-drivers -v $ENA_VER
```

cat /var/lib/dkms/amzn-drivers/2.8.3/build/make.log
DKMS make.log for amzn-drivers-2.8.3 for kernel 6.2.15-100.fc36.x86_64 (x86_64)
Wed May 17 08:42:57 AM PDT 2023
make: Entering directory '/var/lib/dkms/amzn-drivers/2.8.3/build/kernel/linux/ena'
make -C /lib/modules/6.2.15-100.fc36.x86_64/build M=/var/lib/dkms/amzn-drivers/2.8.3/build/kernel/linux/ena modules
make[1]: Entering directory '/usr/src/kernels/6.2.15-100.fc36.x86_64'
warning: the compiler differs from the one used to build the kernel
  The kernel was built by: gcc (GCC) 12.2.1 20221121 (Red Hat 12.2.1-4)
  You are using:           gcc (GCC) 12.0.1 20220413 (Red Hat 12.0.1-0)
  CC [M]  /var/lib/dkms/amzn-drivers/2.8.3/build/kernel/linux/ena/ena_netdev.o
  CC [M]  /var/lib/dkms/amzn-drivers/2.8.3/build/kernel/linux/ena/ena_ethtool.o
  CC [M]  /var/lib/dkms/amzn-drivers/2.8.3/build/kernel/linux/ena/ena_lpc.o
  CC [M]  /var/lib/dkms/amzn-drivers/2.8.3/build/kernel/linux/ena/ena_phc.o
/var/lib/dkms/amzn-drivers/2.8.3/build/kernel/linux/ena/ena_phc.c:112:10: error: ‘struct ptp_clock_info’ has no member named ‘adjfreq’
  112 |         .adjfreq        = ena_phc_adjfreq,
      |          ^~~~~~~
compilation terminated due to -Wfatal-errors.
make[2]: *** [scripts/Makefile.build:252: /var/lib/dkms/amzn-drivers/2.8.3/build/kernel/linux/ena/ena_phc.o] Error 1
make[1]: *** [Makefile:2025: /var/lib/dkms/amzn-drivers/2.8.3/build/kernel/linux/ena] Error 2
make[1]: Leaving directory '/usr/src/kernels/6.2.15-100.fc36.x86_64'
make: *** [Makefile:64: all] Error 2
make: Leaving directory '/var/lib/dkms/amzn-drivers/2.8.3/build/kernel/linux/ena'
```


### Expected Behavior

Compiling without error! 

### Actual Behavior

Failed and returned error as .adjfreq deprecated at kernel version 6.2

### Additional Data

_No response_

### Relevant log output

_No response_

### Contact Details

arshad.rad@gmail.com

**Comment by davidarinzon** [comment] 2023-05-17 21:13
Thank you @mehrdadrad for identifying this and raising a ticket with the relevant information.
We'll address this compilation issue in the next release.

**Comment by amitbern-aws** [comment] 2023-05-18 06:07
@mehrdadrad 
Until the release is ready, you can do one of the following:
1. Remove the ```ENA_PHC_INCLUDE=1``` flag from the compilation, as there are currently no PHC supported devices
2. apply the attached patch to fix the compilation issue 
[phc_kernel_6_2_fix.patch](https://github.com/amzn/amzn-drivers/files/11504862/phc_kernel_6_2_fix.patch)

Thanks

**Comment by davidarinzon** [comment] 2023-05-28 20:24
Hi @mehrdadrad 
The issue is expected to be fixed in version 2.8.7 which was just released (https://github.com/amzn/amzn-drivers/releases/tag/ena_linux_2.8.7), you're welcome to check it and provide feedback.

**Comment by mehrdadrad** [comment] 2023-06-02 16:45
It doesn't work properly! I tested it with kernel 6.2.15-100.fc36.x86_64 and during boot process it's getting stuck randomly. I couldn't catch anything through EC2 serial console because when I try console this issue doesn't happen!!

**Comment by amitbern-aws** [comment] 2023-06-02 17:00
@mehrdadrad 
1. While we appreciate your feedback and value your input,
We've noticed that some of your claims contain exclamation points, 
which can sometimes convey a sense of urgency or frustration. 
While we understand that you may feel strongly about certain matters, 
I wanted to kindly request that we maintain a more neutral tone in our written communication.
By keeping our exchanges courteous and respectful, 
we can ensure that our discussions remain productive and focused on finding solutions to any issues you may encounter. 
Clear and constructive communication will help us serve you better and address your concerns effectively.

2. please elaborate on what "doesn't work properly" , do you still see the "adjfreq" compilation issue? if not please open a new ticket and elaborate on all needed info

Thanks

**Closed** 2023-06-02 18:18 UTC
Labels: bug, Linux ENA driver, triage
