### ISSUE TITLE
Issue with tc matches using ENA instances

### ISSUE THREAD

**Issue by jfoster-twilio** [amzn/amzn-drivers#137] opened 2020-07-31 20:38 UTC
# Background
I've been working with tc filters to match ingress traffic based on UDP destination port(s). In testing, I noticed that when sending UDP payloads in excess of 214 bytes, the filter would not match the traffic towards the target UDP destination port(s). I have observed this behavior on AWS instances with ENA (e.g. c5d, t3) but was not able to reproduce on older generation instances (e.g. t2) which I believe use a different network driver. I believe this may be due to an issue with the ENA driver.

For testing I have setup the following an ingress qdisc with the following filter:
```bash
sudo tc qdisc add dev eth0 handle ffff: ingress
sudo tc filter add dev eth0 parent ffff: protocol ip pref 1 basic match "cmp(u16 at 2 layer transport eq 12400)" action simple sdata "dport_12400"
```

The expectation is that the 2 byte value at offset 2 from the transport header will have value equal to 12400 (e.g. the destination port field equals 12400), and the message `dport_12400` will be printed for matches

The following describes the testing setup I've used for comparison which can be used to reproduce the issue:

# ENA instance
Launch a t3.large instance with Amazon Linux 2 Image (AMI ID amzn2-ami-hvm-2.0.20200722.0-x86_64-gp2 (ami-0873b46c45c11058d))

Install tc and setup the ingress qdisc and filter:
```bash
sudo yum install -y tc
sudo tc qdisc add dev eth0 handle ffff: ingress
sudo tc filter add dev eth0 parent ffff: protocol ip pref 1 basic match "cmp(u16 at 2 layer transport eq 12400)" action simple sdata "dport_12400"
```

Send a UDP packet to (instance public hostname, dport 12400) with payload size 200 bytes

I've used the following python script in my testing
```python
import socket

UDP_IP = "ec2-44-234-39-17.us-west-2.compute.amazonaws.com"
UDP_PORT = 12400

print "UDP target IP:", UDP_IP
print "UDP target port:", UDP_PORT

len = int(input("Please enter a payload length: "))
MESSAGE = "A" * len
print "message:", MESSAGE

sock = socket.socket(socket.AF_INET, # Internet
             socket.SOCK_DGRAM) # UDP
sock.bind(('0.0.0.0', 50020))
sock.sendto(MESSAGE, (UDP_IP, UDP_PORT))
```

Now you should see a match for this packet printed, e.g.:
```bash
dmesg | grep dport_12400
[  100.588139] simple: dport_12400_1
```

Next, send another UDP packet to (instance public hostname, dport 12400) with payload size 400 bytes

Check and see, there was no match printed for the second packet. e.g.
```bash
dmesg | grep dport_12400
[  100.588139] simple: dport_12400_1
```

In my probing, I've found that UDP payloads with length in excess of 214 bytes do not match this filter

# Non-ENA Instance
Now, if you instead launch a t2.large instance with Amazon Linux 2 Image (amzn2-ami-hvm-2.0.20200722.0-x86_64-gp2 (ami-0873b46c45c11058d)), you will find that when running the same tests, UDP packets match the filter as expected (including those whose payload size exceeds 214 bytes).

# Instrumentation
I've done a bit more debugging to try and confirm where the issue lies by instrumenting the kernel module which is doing the matching here (net/sched/em_cmp.c) and found that the following section is where the matching fails for larger packets:
https://github.com/torvalds/linux/blob/master/net/sched/em_cmp.c#L28

The relevant check does the following (https://github.com/torvalds/linux/blob/master/include/net/pkt_cls.h#L493-L499)

```c
static inline int tcf_valid_offset(const struct sk_buff *skb,
				   const unsigned char *ptr, const int len)
{
	return likely((ptr + len) <= skb_tail_pointer(skb) &&
		      ptr >= skb->head &&
		      (ptr <= (ptr + len)));
}
```

In particular the comparison `(ptr + len) <= skb_tail_pointer(skb)` fails for these packets

The following dumps some debugging info re: the SKB and pointer arithmetic here for one of the 400 byte payload packets:
```
[529785.063199] skb len=428 headroom=78 headlen=20 tailroom=0
mac=(64,14) net=(78,20) trans=98
shinfo(txflags=0 nr_frags=1 gso(size=0 type=0 segs=0))
csum(0x0 ip_summed=1 complete_sw=0 valid=0 level=0)
hash(0x21212121 sw=0 l4=1) proto=0x0800 pkttype=0 iif=2
[529785.077834] dev name=eth0 feat=0x0x0000002000004023
[529785.077835] skb linear:   00000000: 45 00 01 ac 8f c3 00 00 3e 11 05 7d 6b 14 a6 1d
[529785.077836] skb linear:   00000010: ac 16 28 b9
[529785.077837] skb frag:     00000000: c3 64 30 70 01 98 27 ed 41 41 41 41 41 41 41 41
[529785.091960] skb frag:     00000010: 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41
[529785.106745] skb frag:     00000020: 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41
[529785.121184] skb frag:     00000030: 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41
[529785.135387] skb frag:     00000040: 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41
[529785.135388] skb frag:     00000050: 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41
[529785.135389] skb frag:     00000060: 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41
[529785.149402] skb frag:     00000070: 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41
[529785.161140] skb frag:     00000080: 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41
[529785.161141] skb frag:     00000090: 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41
[529785.161142] skb frag:     000000a0: 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41 41
[529785.195691] skb frag:     000000b0: 41 41 41 41 41 41 41 41 41 41 41 41
[529785.195693] invalid offset skb=ffff88802c99c400 ptr=ffff8880ba4464e4 ptr2=ffff8880ba4464e6 skb_tail_pointer=ffff8880ba4464e2 skb->head=ffff8880ba446480 cmp->align=2 cmp->off=2 cmp->layer=2 cmp->val=12400 cmp->mask=0
```

Additionally, I've attached the instrumented em_cmp module I used during testing:
```
/*
 * net/sched/em_cmp.c	Simple packet data comparison ematch
 *
 *		This program is free software; you can redistribute it and/or
 *		modify it under the terms of the GNU General Public License
 *		as published by the Free Software Foundation; either version
 *		2 of the License, or (at your option) any later version.
 *
 * Authors:	Thomas Graf <tgraf@suug.ch>
 */

#include <linux/module.h>
#include <linux/types.h>
#include <linux/kernel.h>
#include <linux/printk.h>
#include <linux/skbuff.h>
#include <linux/highmem.h>
#include <linux/tc_ematch/tc_em_cmp.h>
#include <asm/unaligned.h>
#include <net/pkt_cls.h>
#include <net/sock.h>

/* Dump skb information and contents.
 *
 * Must only be called from net_ratelimit()-ed paths.
 *
 * Dumps up to can_dump_full whole packets if full_pkt, headers otherwise.
 */
static void skb_dump(const char *level, const struct sk_buff *skb, bool full_pkt)
{
  static atomic_t can_dump_full = ATOMIC_INIT(5);
  struct skb_shared_info *sh = skb_shinfo(skb);
  struct net_device *dev = skb->dev;
  struct sock *sk = skb->sk;
  struct sk_buff *list_skb;
  bool has_mac, has_trans;
  int headroom, tailroom;
  int i, len, seg_len;

  if (full_pkt)
    full_pkt = atomic_dec_if_positive(&can_dump_full) >= 0;

  if (full_pkt)
    len = skb->len;
  else
    len = min_t(int, skb->len, MAX_HEADER + 128);

  headroom = skb_headroom(skb);
  tailroom = skb_tailroom(skb);

  has_mac = skb_mac_header_was_set(skb);
  has_trans = skb_transport_header_was_set(skb);

  printk("%sskb len=%u headroom=%u headlen=%u tailroom=%u\n"
         "mac=(%d,%d) net=(%d,%d) trans=%d\n"
         "shinfo(txflags=%u nr_frags=%u gso(size=%hu type=%u segs=%hu))\n"
         "csum(0x%x ip_summed=%u complete_sw=%u valid=%u level=%u)\n"
         "hash(0x%x sw=%u l4=%u) proto=0x%04x pkttype=%u iif=%d\n",
         level, skb->len, headroom, skb_headlen(skb), tailroom,
         has_mac ? skb->mac_header : -1,
         has_mac ? skb_mac_header_len(skb) : -1,
         skb->network_header,
         has_trans ? skb_network_header_len(skb) : -1,
         has_trans ? skb->transport_header : -1,
         sh->tx_flags, sh->nr_frags,
         sh->gso_size, sh->gso_type, sh->gso_segs,
         skb->csum, skb->ip_summed, skb->csum_complete_sw,
         skb->csum_valid, skb->csum_level,
         skb->hash, skb->sw_hash, skb->l4_hash,
         ntohs(skb->protocol), skb->pkt_type, skb->skb_iif);

  if (dev)
    printk("%sdev name=%s feat=0x%pNF\n",
           level, dev->name, &dev->features);
  if (sk)
    printk("%ssk family=%hu type=%hu proto=%hu\n",
           level, sk->sk_family, sk->sk_type, sk->sk_protocol);

  if (full_pkt && headroom)
    print_hex_dump(level, "skb headroom: ", DUMP_PREFIX_OFFSET,
             16, 1, skb->head, headroom, false);

  seg_len = min_t(int, skb_headlen(skb), len);
  if (seg_len)
    print_hex_dump(level, "skb linear:   ", DUMP_PREFIX_OFFSET,
             16, 1, skb->data, seg_len, false);
  len -= seg_len;

  if (full_pkt && tailroom)
    print_hex_dump(level, "skb tailroom: ", DUMP_PREFIX_OFFSET,
             16, 1, skb_tail_pointer(skb), tailroom, false);

  for (i = 0; len && i < skb_shinfo(skb)->nr_frags; i++) {
    skb_frag_t *frag = &skb_shinfo(skb)->frags[i];
    u32 p_off, p_len, copied;
    struct page *p;
    u8 *vaddr;

    skb_frag_foreach_page(frag, frag->page_offset,
              skb_frag_size(frag), p, p_off, p_len,
              copied) {
      seg_len = min_t(int, p_len, len);
      vaddr = kmap_atomic(p);
      print_hex_dump(level, "skb frag:     ",
               DUMP_PREFIX_OFFSET,
               16, 1, vaddr + p_off, seg_len, false);
      kunmap_atomic(vaddr);
      len -= seg_len;
      if (!len)
        break;
    }
  }

  if (full_pkt && skb_has_frag_list(skb)) {
    printk("skb fraglist:\n");
    skb_walk_frags(skb, list_skb)
      skb_dump(level, list_skb, true);
  }
}

static inline int cmp_needs_transformation(struct tcf_em_cmp *cmp)
{
  return unlikely(cmp->flags & TCF_EM_CMP_TRANS);
}

static int em_cmp_match(struct sk_buff *skb, struct tcf_ematch *em,
      struct tcf_pkt_info *info)
{
  struct tcf_em_cmp *cmp = (struct tcf_em_cmp *) em->data;
  unsigned char *ptr = tcf_get_base_ptr(skb, cmp->layer) + cmp->off;
  u32 val = 0;
    
    unsigned char *ptr2 = ptr + cmp->align;
    unsigned char *tail_ptr = skb_tail_pointer(skb);
    unsigned char *head_ptr = skb->head;

  if (!tcf_valid_offset(skb, ptr, cmp->align)) {
        skb_dump(KERN_INFO, skb, true);
        pr_info("invalid offset skb=%p ptr=%p ptr2=%p skb_tail_pointer=%p skb->head=%p cmp->align=%u cmp->off=%u cmp->layer=%u cmp->val=%u cmp->mask=%u\n", skb, ptr, ptr2, tail_ptr, head_ptr, cmp->align, cmp->off, cmp->layer, cmp->val, cmp->mask);
    return 0;
    }

  switch (cmp->align) {
  case TCF_EM_ALIGN_U8:
    val = *ptr;
    break;

  case TCF_EM_ALIGN_U16:
    val = get_unaligned_be16(ptr);

    if (cmp_needs_transformation(cmp))
      val = be16_to_cpu(val);
    break;

  case TCF_EM_ALIGN_U32:
    /* Worth checking boundries? The branching seems
     * to get worse. Visit again.
     */
    val = get_unaligned_be32(ptr);

    if (cmp_needs_transformation(cmp))
      val = be32_to_cpu(val);
    break;

  default:
    return 0;
  }

  if (cmp->mask)
    val &= cmp->mask;

    //pr_info("em_cmp val=%u cmp->val=%u cmp->mask=%u cmp->off=%u cmp->align=%u cmp->layer=%u cmp->opnd=%u\n", val, cmp->val, cmp->mask, cmp->off, cmp->align, cmp->layer, cmp->opnd);
  switch (cmp->opnd) {
  case TCF_EM_OPND_EQ:
    return val == cmp->val;
  case TCF_EM_OPND_LT:
    return val < cmp->val;
  case TCF_EM_OPND_GT:
    return val > cmp->val;
  }

  return 0;
}

static struct tcf_ematch_ops em_cmp_ops = {
  .kind	  = TCF_EM_CMP,
  .datalen  = sizeof(struct tcf_em_cmp),
  .match	  = em_cmp_match,
  .owner	  = THIS_MODULE,
  .link	  = LIST_HEAD_INIT(em_cmp_ops.link)
};

static int __init init_em_cmp(void)
{
    //pr_info("em_cmp Loaded\n");
    return tcf_em_register(&em_cmp_ops);
}

static void __exit exit_em_cmp(void)
{
  tcf_em_unregister(&em_cmp_ops);
}

MODULE_LICENSE("GPL");

module_init(init_em_cmp);
module_exit(exit_em_cmp);

MODULE_ALIAS_TCF_EMATCH(TCF_EM_CMP);
```

**Comment by akiyano** [comment] 2020-07-31 22:32
Hi @jfoster-twilio,

Thanks for reporting this issue with such detailed reproduction steps!
What you are describing rings a bell and seems related to a fix to some other issue we are currently working on.
Please check if the attached patch fixes the issue for you and let me know.

To do that please follow these steps:
1. Copy the patch to amzn-drivers directory.
2. Run the following command from inside the amzn-drivers directory to patch the driver:
`git am 0001-copy-pkt-headers-to-skb-inline-data.patch.txt `
3. Build and install the patched driver
4. Run the test that reproduces the issue for you and see if it still happens.

[0001-copy-pkt-headers-to-skb-inline-data.patch.txt](https://github.com/amzn/amzn-drivers/files/5009251/0001-copy-pkt-headers-to-skb-inline-data.patch.txt)

Thanks,
Arthur

**Comment by jfoster-twilio** [comment] 2020-07-31 23:10
Hi @akiyano, thanks for the quick response! My initial tests indicate the patch resolves the reported issue. Would you mind updating this when the patch lands?

**Comment by akiyano** [comment] 2020-08-01 02:21
Hi @jfoster-twilio ,

Great to hear it solves your issue!
I will update this ticket once we release the fix. 
The fix will not be part of the next release, since it is already closed and will be released soon.
But will probably be in the release after that. 

Thanks,
Arthur

**Comment by jfoster-twilio** [comment] 2021-06-02 19:59
@akiyano Any updates on when this will make it into a release?

**Comment by akiyano** [comment] 2021-06-02 21:09
Hi @jfoster-twilio,

Sorry for not updating here.
Please try it out with the latest 2.5.0 driver, which contains the fix to your issue.

Thanks,
Arthur

**Closed** 2021-09-29 11:14 UTC
